### ISSUE TITLE
No Blank or Null Defaults

### ISSUE THREAD

**Issue by allisonletts** [acrosman/Salesforce2Sql#100]
**Summary**
Preference option: columns do not have a specified default

**Please describe the problem you are trying to solve.**
Talend really wants to respect the defaults, and so I often end up going back in and clearing defaults.
Like, just don't include default in the column definition at all.

Instead of 
``` sql
create table `Account` (`Id` varchar(18) default '', `Name` varchar(255) default '')
```
I'd do
``` sql
create table `Account` (`Id` varchar(18), `Name` varchar(255))
```

I ended up doing this with my Contacts table anyway, and Talend liked it much better, honestly.
**Proposed Solution**
Add it to the preferences list.

**Comment by allisonletts** [comment]
I'm perfectly happy to get the defaults that actually **mean** something. I just don't like the ones that make Talend fight with me more.

**Comment by acrosman** [comment]
Will need to check if this is a behavior of the library being used for SQL generation.  Blank vs null is important and nearly always annoying when it matters.

**Comment by acrosman** [comment]
What happens when you uncheck the box to set blank default in preferences?  Does that achieve the desired result?
<img width="259" alt="image" src="https://user-images.githubusercontent.com/2972053/142810476-97911730-2afc-41cb-a05e-4f67bb4cb622.png">

**Comment by acrosman** [comment]
@allisonletts I think this is supported currently. Please re-open if there is a bug I should address or I misunderstood the ask.
