### ISSUE TITLE
Too Many String Fields stalls schema creation

### ISSUE THREAD

**Issue by selfuntitled** [acrosman/Salesforce2Sql#113]
**Describe the bug**
When a table involves too many string fields, the console correctly reports "Warning: Proposed Lead schema had too many string fields for your database. All strings will be text fields instead." But schema creation stops and the UI stalls/freezes and the table is never created. Eventually the app freezes and grey screens without evidence of retries.

**To Reproduce**
See me for an example SQL file.
Load the file, and click Generate SQL.
Creating Database spinner spins, show console log shows the above error.

**Expected behavior**
App will replace varchar with text and the table will be created.
Note - as a work-around confirmed this strategy works.  Often all it takes is replacing only varchar where size is > 255 Characters.
In one cases where that strategy didn't work, reduced all Varchar 255 to 250 and the table inserted.

**Screenshots**
![image](https://user-images.githubusercontent.com/1082358/149211937-93405926-9f9c-41bc-8880-9b534a41bbb0.png)

**Desktop (please complete the following information):**
 - OS: Windows Server
 - Target Database: MariaDB

**Additional context**

**Comment by acrosman** [comment]
It should be replacing all those Varchar fields with Text fields to avoid that limit. I'll have to investigate why that's the case.

**Comment by acrosman** [comment]
I think this is actually related #110.  Also the interface could stand to be improved to give me feedback during the process of creating tables which can take a few minutes to complete.

**Comment by acrosman** [comment]
@selfuntitled if you want to re-test this, you can clone the repo and run from the current main branch to see if the problem persists.

**Comment by acrosman** [comment]
There are some cases where this still persists.  Working on additional adjustments.
