### ISSUE TITLE
Always index Id fields

### ISSUE THREAD

**Issue by selfuntitled** [acrosman/Salesforce2Sql#114]
**Summary**
When importing Salesforce data - ID is always going to be useful joins and uniqueness purposes.
Often it's important to have to avoid duplicating rows during data import.

**Please describe the problem you are trying to solve.**
When I re-run an extract from Salesforce, I want it to fail ugly if it's about to append a duplicate data set to the table. 

**Proposed Solution**
All fields named Id get a unique index.

**Comment by acrosman** [comment]
There is an option for this in the preferences today. It drives the detection by field type not name.

**Comment by acrosman** [comment]
Looks like there is an issue where these columns aren't getting indexed.  Created a PR to fix
