### ISSUE TITLE
Save/Load Salesforce Schema for Replay

### ISSUE THREAD

**Issue by allisonletts** [acrosman/Salesforce2Sql#13]
I’d like to be able to save the output of a schema. 
@acrosman what other detail would be helpful to build this out?

**Comment by acrosman** [comment]
As I understand the ask (and is something I want to see added) it would be helpful to Save the list of objects and fields for easy alteration of the generation process and replay of the database build process.

**Comment by acrosman** [comment]
#14 adds a save function that drops the selected schema elements to a JSON file.  Still need to work out when to load the file and how to validate/update it against the selected org.
