### ISSUE TITLE
Set Checkboxes to default false when no default set

### ISSUE THREAD

**Issue by acrosman** [acrosman/Salesforce2Sql#195]
**Summary**
For boolean fields, when no default is set in Salesforce, default field to null

**Please describe the problem you are trying to solve.**
Salesforce does not allow pushing Null to checkbox fields.  Since this is meant to support migrations, we want to make sure data in fields can be sent by default to any writable field.

**Proposed Solution**
Add a default to checkbox fields to set them false if no default is provided in the describe.

**Comment by AnshulKahar2729** [comment]
@acrosman that can be easily done by javascript. Assign me the issue so that I can resolve it and make a PR.
