### ISSUE TITLE
Add settings for Database options

### ISSUE THREAD

**Issue by acrosman** [acrosman/Salesforce2Sql#30]
**Summary**
Adding settings to change some behaviors and assumptions about how to translate Salesforce fields.

**Please describe the problem you are trying to solve.**
Depending on the use case some standard SF fields might be useful in a couple different forms.  Having settings to controls those could be helpful.  For example, the main record ID field might be more useful in some settings as an auto number, or plain integer than as an SFID. Another example would be RecordTypeIDs being set as the record type name on the assumption it would be translated during later processing.

**Proposed Solution**

Add the following settings to the preferences:
- [x] Allow Picklists to be Varchar(255) instead of Enums.
- [x] Make Picklist to string when the Salesforce value is unrestricted.
- [x] Include a blank option in all Enums (instead of just null).
- [x] Default lookups fields to indexed.
- [x] Default to make picklists indexed.
- [x] Allow lookups to default to: char(18), varchar(255) (or text when varchars are too numerous).
- [x] Allow setting of default value to field default.
- [x] Default all text values to empty string instead of null.

Additionally:

- [x] #34
- [ ] #57
- [ ] #58

PRs for any individual piece happily considered. Please do _not_ comment that prs that fix a piece will fix or close this issue.

**Comment by allisonletts** [comment]
My default values aren't being set properly. Defaults for Varchar(255)s are set without being enclosed in single quotes, so they aren't quite working in practice.
![image](https://user-images.githubusercontent.com/17914696/129592834-ab1c26bc-0949-41b5-b422-8fd2e25387a5.png)
