### ISSUE TITLE
Predefined templates

### ISSUE THREAD

**Issue by allisonletts** [acrosman/Salesforce2Sql#33]
**Summary**
I'd like to be able to say "we use case teams" or "we use pricebooks" or other common features and have the tool check more objects for my schema

**Please describe the problem you are trying to solve.**
I wish I didn't have to try to remember which objects are included within a particular Salesforce feature.

**Proposed Solution**
Show a list of features to add or remove using checkboxes. Use the checkboxes drive the selected objects for the schema. This could be a "step 1" where "step 2" is customizing with more granularity (the existing detailed selection).

**Comment by acrosman** [comment]
The current object selection process is very light weight: it detects NPSP or EDA, and makes simplistic guesses about additional standard objects you might care about from there. It also assumes you care able every custom object in every managed packages -- which is also a weak assumption.  So yes, there is lots of room for improvement here. I've been pondering the idea of having the ability to check/uncheck packages by namespace in a group, but they doesn't help with the standard objects that come along for the ride.

It would be help to have a list of specific patterns that you'd find useful, and the objects that should be selected as a consequence.

**Comment by acrosman** [comment]
There have been several improvements to the selection interface since this was opened, but there is still room for more.  It would be helpful to get a list of suggested feature sets to include and what those when enable-disable. This could become an endless list so it would require some care about how to drive it well, but I'm interested in ideas and suggestions.

**Comment by acrosman** [comment]
I think I'd like to use #105 for carrying this any further than the three detected org types currently.
