### ISSUE TITLE
Option to exclude read-only fields

### ISSUE THREAD

**Issue by allisonletts** [acrosman/Salesforce2Sql#34]
**Summary**
If I'm creating a schema to plan a migration, I want to ignore the R/O fields.

**Please describe the problem you are trying to solve.**
It's hard to tell which fields shouldn't be mapped to, even though it'll throw an error in SF.

**Proposed Solution**
Options: 

- create the column but set the default to ReadOnly or something so that it's scannable from talend
- don't create the column at all

**Comment by acrosman** [comment]
How do you suggest determining which fields should be read only?  Formulas are pretty clear, but what else would make sense.  The API provides a value of `createable` and `updateable` in the response that could be leveraged, but I'm not sure if those are specific to the user running the query or not.  I could also see use case specific exceptions that might make this an extensions of #30.  Suggestions welcome.
