### ISSUE TITLE
Add Jest tests

### ISSUE THREAD

**Issue by acrosman** [acrosman/Salesforce2Sql#48]
**Summary**
We need automated testing. Since Jest is SFDC's library of choice seems like the right choice here.

**Comment by imrishabh18** [comment]
Hey @acrosman! Can you give more context on this pls? I would like to take this up

**Comment by acrosman** [comment]
#49 (which I'm going to merge sometime today -- once I get the last of the new checks to pass) will put the initial pieces in place. Once that's done I'll replace this issue with a few that are more fine grained about where there are gaps in test coverage (there is very little coverage at the moment), and where the tests to need new features.  

The big challenge on this project is writing tests that work with Electron and Knex in a useful way (either via mocks or additional dependencies.

But given that there is very little coverage now there is lots of low handing fruit in all parts of the project.  #49 provides several commits near the end that outline a few ways to setup tests for the `sf_calls.js` module, but again any tests on any part of the application are welcome.

**Comment by acrosman** [comment]
@imrishabh18 you might review #63 for suggestions on next steps.
