### ISSUE TITLE
Select All/ Deselect All After Object Fetch

### ISSUE THREAD

**Issue by MDeBaise1** [acrosman/Salesforce2Sql#79]
Add a Select All/ Deselect All checkbox for object selection.

After fetching all objects having a checkbox to Select All/ Deselect All to make it easier to grab only needed objects faster.

**Comment by acrosman** [comment]
There is much room for improvement of the object selection interface.  This is related to #33 which makes a different, but related ask, and my comments on that issue extend the idea as well. All of those suggestions should be included.

**Comment by allisonletts** [comment]
I needed this just before this release :smile: glad you made it happen.
