### ISSUE TITLE
Default values aren't consistently being set properly.

### ISSUE THREAD

**Issue by acrosman** [acrosman/Salesforce2Sql#80]
My default values aren't being set properly. Defaults for Varchar(255)s are set without being enclosed in single quotes, so they aren't quite working in practice.
![image](https://user-images.githubusercontent.com/17914696/129592834-ab1c26bc-0949-41b5-b422-8fd2e25387a5.png)

_Originally posted by @allisonletts in https://github.com/acrosman/Salesforce2Sql/issues/30#issuecomment-899622889_

**Comment by allisonletts** [comment]
I'm running MariaDB through HeidiSQL.

**Comment by acrosman** [comment]
I'm also wonder about the field settings for that specific field. From the screen shot it looks like other were set differently right around it so I'd like to know what that one includes to see why it's different.

**Comment by allisonletts** [comment]
the ``` DEFAULT '0' ``` is for a TinyInt -- is that what you're looking at?

**Comment by acrosman** [comment]
I'm not able to reproduce this at the moment. I did notice that it's not properly pulling defaults for all fields, but I'm not sure if the fix I just posted to #85 is correct for that or for this.  Would appreciate re-testing with that branch to see if it behaves better (also should be much faster than release v0.4.0 so the testing should be too bad).

**Comment by allisonletts** [comment]
This can be closed for now as a pebkac, I think.
