### ISSUE TITLE
Account always included in retrieved schemas

### ISSUE THREAD

**Issue by allisonletts** [acrosman/Salesforce2Sql#97]
**Describe the bug**

**To Reproduce**
1. create new connection
2. retrieve objects
3. deselect all objects, select two that are not Account (or more, I imagine)
4. generate SQL
5. See that Account is included in the list of retrieved schemas

**Expected behavior**
The schemas of the selected objects are retrieved

**Screenshots**
Last Response:
![image](https://user-images.githubusercontent.com/17914696/141534772-84f7d947-a539-4793-b45d-9caca4b781e3.png)

Message Console:
![image](https://user-images.githubusercontent.com/17914696/141535019-795c7562-e2a2-4974-8952-e7875bfb3cfb.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2019
 - Target Database: MariaDB

**Additional context**
It's weird to me that the objects list in the response is right, but the schema list is wrong.

**Comment by allisonletts** [comment]
Update: running the create tables function attempted to insert the Account table. It was unsuccessful because I left "drop and recreate" unchecked.

**Comment by acrosman** [comment]
That is weird.  I'll figure it out.

**Comment by allisonletts** [comment]
This may be from a release or two ago. If it's not reproduceable on your end, I can find the release I'm using. I will say I don't think I've seen this before.

**Comment by allisonletts** [comment]
I'm going to close this for now. Just installed the latest version from source and I'm not having a problem.

**Comment by allisonletts** [comment]
@acrosman OOOOOOOHHHHHHH
It happens if you do the describe and move on to the proposed schema and then change your mind and go back to org objects and uncheck.
I actually don't know how to start over and/or tell it to completely freshly create the schema without anything it had before.

**Comment by acrosman** [comment]
Needs to be considered when resolving #107 and #101.
