### ISSUE TITLE
Add more detail to creating database tables loader message

### ISSUE THREAD

**Issue by allisonletts** [acrosman/Salesforce2Sql#99]
**Summary**
Consider including a check every minute or so of the "Creating Database Tables" message

**Please describe the problem you are trying to solve.**
At some point, "Creating Database Tables" next to a spinning wheel looks like it might be a mistake.

**Proposed Solution**
If the message said `Creating Database Tables. Last checked 11/13/21 9:14 PM` I'd feel less inclined to check the actual database to see what had been created. At what points do you get information back? I'm not sure how doable this is, and I'd be happy to chat about alternative solutions.

**Comment by acrosman** [comment]
Create tables should provide a count of what's been done and update the interface as it goes.  There are also lots of messages that go to the logs that could be useful to display to the user as it runs.

**Comment by allisonletts** [comment]
I was running 0.5.0 and it must have errored out at some point, because it ended up spinning overnight without telling me anything. The log stopped updating longgggg before I posted this (like 1/2 hour of no log update--I went and did something else).

It appears that having all of the lookups on Contact set to varchar(255) even when everything else was autofixed to text was still too big of a row. Happy to do a screenshare.

**Comment by acrosman** [comment]
Related to #96

**Comment by acrosman** [comment]
Looks like the handling of promises generated by Knex is all kinds of misaligned causing the main thread to think all the promises related to the database creation have resolved when they are still pending. It'll take a bit of untangling to get this working right (and that untangling is probably needed).
